### ISSUE TITLE
Po wymianie licznika nie pokazuje nowych wartości, a tylko ostatnią najwyższą

### ISSUE THREAD

**Issue by ChrisPolewiak** [pawelhulek/pgnig-sensor#20]
Po wymianie licznika nie pokazuje nowych wartości, a tylko ostatnią najwyższą

**Comment by pawelhulek** [comment]
Czesc, 
dzieki za zgłoszenie,
To moze byc trudny orzech do zgryzienia, ale pomyśle jak ten problem rozwiązać.

@ChrisPolewiak zalogowałbys sie do portalu pgnig ebok i sprawdził ile masz liczników po wykonaniu zapytania 
https://ebok.pgnig.pl/crm/get-ppg-list?api-version=3.0

Obawiam się, że 1, ale jeśli masz podpiete to pod inny licznik to mam nadzieje ze problem rozwiąze sie wraz z https://github.com/pawelhulek/pgnig-sensor/issues/17

**Comment by Santanachia** [comment]
mam podobny problem (sensor jest niedostępny), tylko nie wiem czy to po wymianie licznika, czy po aktualizacji do nowej bety

get-ppg-list pokazuje jeden licznik, na dodatek `MeterNumber` jest ten sam.
get-all-ppg-readings-for-meter pokazuje nową wartość

**Comment by pawelhulek** [comment]
Ok, to ja dopisze funkcjonalnosc zeby zamiast najwyzszej wartosci to czytana byla ostatania. Ale moze to spowodowac zjazd z np 2000 KW do 0KW przy wymianie licznika.

**Comment by Santanachia** [comment]
https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-total_increasing
z tego co widzę, można zrobić tak by licznik się zerował a suma przyrastała nadal.

**Comment by Santanachia** [comment]
@pawelhulek Hej, sensor nadal pokazuje najwyższą, a nie ostatnią wartość :(

**Comment by Santanachia** [comment]
Super, pokazuje aktualną wartość

**Comment by dzikus** [comment]
Potwierdzam, u mnie także jest ok.
