### ISSUE TITLE
pgnig_gas_sensor: Error on device update!

### ISSUE THREAD

**Issue by tomhash2** [pawelhulek/pgnig-sensor#22]
W moim przypadku nie pokazuje się info o fakturze ponieważ:

`2022-06-17 21:15:33 ERROR (MainThread) [homeassistant.components.sensor] pgnig_gas_sensor: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 168, in async_update
    self._state = await self.hass.async_add_executor_job(self.invoices_summary)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 179, in invoices_summary
    next_payment_item = min(filter(upcoming_payment_for_meter, self.api.invoices().invoices_list), key=lambda z: z,
TypeError: '<' not supported between instances of 'InvoicesList' and 'InvoicesList'`

Trudno mi powiedzieć dlaczego tak się dzieje, ale mam dwie faktury do zapłaty. Czy to może być powód?
Tomek.

**Comment by luzik** [comment]
u mnie to samo..

**Comment by pawelhulek** [comment]
@luzik @tomhash2 opublikowalem bete sensora pod tagiem: https://github.com/pawelhulek/pgnig-sensor/releases/tag/2.2.0-beta. Sprawdzicie prosze czy teraz ostatnia faktura poprawnie sie wyświetla?

**Comment by luzik** [comment]
HACS nie pokazuje bety

**Comment by pawelhulek** [comment]
@luzik Zobacz prosze w zakldce HACS -> PGNIG sensor -> ... w prawym gornym rogu - > redownload -> show beta version. Wtedy powinna sie pojawic wersja 2.2.0-beta

**Comment by luzik** [comment]
Mam przypisane do konta dwa liczniki. Stany liczydeł są poprawnie z obu. Faktura tylko jedna, druga pokazuje 0 i puste atrybuty

**Comment by pawelhulek** [comment]
@luzik a czy to sie zgadza ze stanem z eboku?
Tam tez masz tylko 1 fakture?

**Comment by luzik** [comment]
Nie do końca rozumiem co powinienem widzieć. Mam dwie umowy.
1.
a) boa
Jak w boa filtruję fv z umowy A - widzę listę opłaconych faktur - bilans do zapłaty jest 0 bo wszystko opłacone.
b) integracja
wartosc 0, atrybyty puste

2.
a) boa
bilans XXX PLN
b) integracja
wartosc XXX, atrybuty uzupełnione
