### ISSUE TITLE
Śledzenie kosztów

### ISSUE THREAD

**Issue by Santanachia** [pawelhulek/pgnig-sensor#26]
Hej, czy jest szansa by dane z `sensor.pgnig_gas_invoice_sensor_xxx` mogły być użyte do śledzenia kosztów?
Mamy takie okienko:
![image](https://user-images.githubusercontent.com/4628507/178224489-f11ec8c7-144b-44a9-9da4-034067a2af0b.png)
ale w nim nie można wybrać sensora z tej integracji :(

**Comment by pawelhulek** [comment]
Dodam to w ramach #25
