### ISSUE TITLE
Dashboard Energia

### ISSUE THREAD

**Issue by yack1** [pawelhulek/pgnig-sensor#35]
Cześć korzystam z ten integracji. Encje mi sie pojawiają i wyświetlają dobre wartości 
![2022-08-10_11h45_40](https://user-images.githubusercontent.com/72358225/183871468-37924244-bce5-483a-be77-89ed9174dfda.jpg)
Nie mniej jednak dodając encję do Dashboardu Energia nie pojawia mi sie żadna wartość w zakładce Energia- jest 0 m3.
![2022-08-10_11h49_11](https://user-images.githubusercontent.com/72358225/183871832-3e53bc7d-e5b3-4ae9-addb-02d33a7d6567.jpg)
![2022-08-10_11h50_53](https://user-images.githubusercontent.com/72358225/183872030-5a18fe5e-8808-4e7c-9d04-d24c4bc3f90b.jpg)
Nie  wiem czy widać załaczone obraki ?

**Comment by kamyk** [comment]
Witam,

Chciałbym zapytać i nie otwierać kolejnego tematu. Dodałem do zakładki Energy i jak widać zostały pobrane dwie wartości z PGNIG. Jednak nadal nie mam tych wartości w zakładce Energy. Czy coś mogę zmienić, żeby to się pojawiało? 

![Screenshot 2024-03-11 at 15 19 04](https://github.com/pawelhulek/pgnig-sensor/assets/1186538/752849ea-97ea-41ef-afb5-f416ad6bdccb)

Świetna integracja! Gratuluję.

**Comment by pawelhulek** [comment]
W zakładce energy wartosci powinny sie pokazywac w dniu ich pobrania - ewentualnie mozesz zmienic widok na miesieczny.

**Comment by kamyk** [comment]
Witam,
A w którym miejscu zmienić na miesięczny?
Pozdrawiam

pon., 11 mar 2024, 19:24 użytkownik Paweł Hulek ***@***.***>
napisał:

**Comment by kamyk** [comment]
A jeszcze dodam, że jak dodałem koszt to pokazuje taki błąd:

![Screenshot 2024-03-12 at 11 20 03](https://github.com/pawelhulek/pgnig-sensor/assets/1186538/276b37f9-ebd9-448d-ad20-5f0451e2a668)

Pewnie coś źle robię.
Pozdrawiam

**Comment by kamyk** [comment]
Witam,

Które Entity mam podać i gdzie dokładnie, żeby widzeć te dane z FV?

<img width="1687" alt="Screenshot 2024-03-13 at 11 56 41" src="https://github.com/pawelhulek/pgnig-sensor/assets/1186538/9ab22a0f-3270-4e5c-bbcd-566498da0c89">

**Comment by kamyk** [comment]
@pawelhulek - czy jest szansa to jakoś ogsarnąć? Nie mam pojecia jak dodać do dashboardu.

<img width="435" alt="Screenshot 2024-03-14 at 12 27 09" src="https://github.com/pawelhulek/pgnig-sensor/assets/1186538/610eb63a-8aee-4518-b849-6a982ed3346f">

**Comment by pawelhulek** [comment]
Hej, wlasciwie to jest bug. 
Jakbys otworzyl nowe issue to bylbym wdzieczny
