### ISSUE TITLE
błędna cena gazu

### ISSUE THREAD

**Issue by Santanachia** [pawelhulek/pgnig-sensor#36]
Hej,
1. Ilość gazu podawana jest w m3, cena za kWh. Niestety będzie to źle liczyło koszty w dashboardzie z energią (o ile uda się dodać)
2. Wartość też nie jest poprawna. Sensor pokazuje `0,185240449438202 PLN/kWh`, natomiast według FV mam 0,22452 PLN/kWh
![image](https://user-images.githubusercontent.com/4628507/184361216-2deec377-3c78-4255-90df-5af82b099b76.png)
nawet jeśli podzielę kwotę końcową przez ilość kWh, to nie wychodzi to co w sensorze (wtedy jest 0,30862...)

**Comment by pawelhulek** [comment]
ojojoj. racja - wybierana jest nie najnowsza faktura a najstarsza ;(

**Comment by Santanachia** [comment]
@pawelhulek a co z 1.?

**Comment by pawelhulek** [comment]
@Santanachia a czemu bedzie liczyło błędnie? Podana jest jednostka miary: unit_of_measurement: PLN/kWh, wydaje mi sie ze powinno to zostac poprawnie przeliczone.

**Comment by Santanachia** [comment]
@pawelhulek a skąd HA ma wiedzieć ile kWh jest z jednego m3?

**Comment by pawelhulek** [comment]
Nie no oczywiscie masz racje.

Potestuje sobie jeszcze, bo integracja w miare dobrze poprzeliczala sobie - ale bez 100% dokładnosci, walidacja wymagała tez podania miary i przepuscila PLN/KWH. Postaram sie na dniach wrócić z poprawka

**Comment by Santanachia** [comment]
to może dorzuć jeszcze jeden sensor?
w https://ebok.pgnig.pl/crm/get-invoices-v2 jest `WearKWH`, więc do dashboarda z energią można podpiąć zużycie w kWh i cenę w PLN/kWh

**Comment by Santanachia** [comment]
@pawelhulek od tygodnia jest wartość z wyliczenia kwota z FV/ilość kWh z FV.
czyli doliczasz opłaty stałe. No ale to mniej istotne.
Czy nie mógłbyś podać w ten sposób wyliczonej kwoty za m3?

**Comment by pawelhulek** [comment]
W wersji Beta v2.3.3 została opublikowana z poprawka. Daj znac co o tym sadzisz to pojdzie do głownego kanału releasów.

**Comment by Santanachia** [comment]
Wygląda że to jest najlepsze co da się osiągnąć

Dzięki :)
