### ISSUE TITLE
86066a2d.js:1 RangeError: Invalid currency code : PLN/kWh

### ISSUE THREAD

**Issue by MG-Sky** [pawelhulek/pgnig-sensor#40]
Czesc, sporo błędów dla kafelka w trybie developerskim sie pojawia:
RangeError: Invalid currency code : PLN/kWh
    at new NumberFormat (<anonymous>)
    at A (86066a2d.js:1:35223)
    at h (95446709.js:1:1244)
    at p (95446709.js:1:922)
    at l.value (state-card-display.ts:42:1)
    at l.update (styles.ts:370:1)
    at l.performUpdate (styles.ts:370:1)
    at l.scheduleUpdate (styles.ts:370:1)

cos u ciebie - czy mozna zignorowac ten error?

**Comment by pawelhulek** [comment]
A ktora to wersja? Dodatkowo który kafelek masz na  mysli? Energy? Przez tryb developerski rozumiem masz na mysli konsole przegladarki?

**Comment by MG-Sky** [comment]
hej, wersja teraz 2.3.3 ale czerwono w deweloperskim w przeglądarce kafelek jest glance dla wszystkich 3 encji.

**Comment by pawelhulek** [comment]
@MG-Sky nie mam pojecia jak to ugryść - HA wymaga odemnie podawania PLN/m³ jako unitu, bo inaczej nie odczyta tej zmiennej - u mnie sie sypie tez na innych currencies - wydaje sie to problem raczej frontendu HA niz integracji.

Zostawie otwarty ten wątek, moze na cos natrafie i sie uda poprawic.

**Comment by pawelhulek** [comment]
@MG-Sky Czy problem dalej wystepuje. W najnowszym HA nie wyskakuje to w konsoli.
