### ISSUE TITLE
Lack of cost tracking sensor value


### ISSUE THREAD

**Issue by rotherpawel** [pawelhulek/pgnig-sensor#43]
Kontynuacja https://github.com/pawelhulek/pgnig-sensor/issues/41

Wersja ha core: 2022.9.7
Wersja PGNiG: 2.3.4

Przyszła mi właśnie faktura na PGNiG. Integracja ją zauważyła, encja invoice ustawiła się poprawnie jednakże encja cost tracking nie zmieniła swojego stanu: nadal jest unknown. 
![IMG_20220927_093430.jpg](https://user-images.githubusercontent.com/85416536/192463969-457049db-d49e-4475-8ab0-e230b9f5c0cb.jpg)

W logach ha core nie widzę żadnego warninga/errora

**Comment by pawelhulek** [comment]
@rotherpawel 
Mógłbys zalogowac sie na pgnig i otworzyc ten link:
https://ebok.pgnig.pl/crm/get-invoices-v2?pageNumber=1&pageSize=12&api-version=3.0

powinny Ci sie wysweitlic wszystkie invoicy. Generalnie beda one odfiltrowane jesli nie ma wear albo GrossAmount

**Comment by rotherpawel** [comment]
Mam listę faktur, ogólnie dla 2 liczników, ale sytuacja jest taka sama dla obu. Mianowicie ostatnia faktura z 1 licznika:
`{
      "Number": "P/41128637/0009/22",
      "Date": "2022-09-26T00:00:00.000000Z",
      "SellDate": "2022-09-01T00:00:00.000000Z",
      "GrossAmount": 45.360,
      "AmountToPay": 45.360,
      "Wear": 0.0,
      "WearKWH": 136.000,
      "PayingDeadlineDate": "2022-10-10T00:00:00.000000Z",
      "StartDate": "2022-08-27T00:00:00.000000Z",
      "EndDate": "2022-09-30T00:00:00.000000Z",
      "IsPaid": false,
      "IdPP": "916215",
      "Type": "PPG",
      "TempType": "E",
      "DaysRemainingToDeadline": 0,
      "HasIban": true,
      "Iban": "51 1020 1026 9000 0004 1128 6371",
      "Status": "NotPaid",
      "PdfExists": false,
      "IsInterestNote": false,
      "Color": "#0055ff",
      "AgreementName": "romanowski",
      "AgreementNumber": "HZ9006031/2019",
      "IsAdditionalAgreement": false,
      "AgreementEndDate": null,
      "AgreementExpired": false,
      "PDFPrintAllowed": true,
      "PaymentProcessAllowed": true,
      "AgreementHasCard": false,
      "AutomaticPaymentDate": "2022-10-08T00:00:00.000000Z",
      "IsInsurancePolicy": false,
      "IsLawyerAgreement": false,
      "IsPersonalSecurityAgreement": false
    },`
    
    Jak widać w tej fakturze jak i w każdej innej   **"Wear": 0.0** . Czy to tutaj jest błędem?

**Comment by pawelhulek** [comment]
Ajajaajaj - masz podane wartosc tylko w KWH a nie masz w m3 - moge ewentualnie pomyslec nad tym zeby sie robila encja z liczeniem kosztu dla KWH ale to sie chyba dobrze nie wyswietli

**Comment by rotherpawel** [comment]
A to jest jakoś "ustawialne" z poziomu pgnig? Czy to bug po ich stronie?

**Comment by pawelhulek** [comment]
@rotherpawel nie powiedziałbym ze to jest bug - To API nie jest oficialnym API - to jest to co Ci dostarczaja do UI - moze to poprsotu tak ma byc - jesli jestes w stanie debuggowac API to moze ta informacja bedzie w twoim przypadku dostepna w innym miejscu. Na dobra sprawe to w PGNIG m3 sa wyswietlane tylko w UI - moze to byc taka kwestia ze u wyswietlanie tej informacji u innych osob jest bugiem. 

Spróbuje poszukac gdzies po API współczynnika konwersji to moze sie uda to w Twoim przypadku poprostu przeliczac.
W ostatecznosci mozna by próbowac rozczytac fakture - ale to jest juz gruba przeróbka aplikacji ;(

**Comment by rotherpawel** [comment]
@pawelhulek Szkoda, że w tym jsonie nie wysyłają bezpośrednio wsp. konwersji. :( Jedyne co mi się znaleźć udało to w UI wyliczają zućycie w kWh na podstawie uniwersalnego wsp. konwersji 10,972 i pokazuje mi się 132kWh, ale i tu jest rozjazd, bo na fakturze mam wsp. konwersji 11,342 i zużycie 136kWh.

**Comment by Santanachia** [comment]
jeśli do wyliczenia potrzebujemy `Wear`, to możemy to wziąć z https://ebok.pgnig.pl/crm/get-all-ppg-readings-for-meter?pageSize=1&pageNumber=1&api-version=3.0&idPpg=<tuNumerLicznika>

**Comment by pawelhulek** [comment]
Nie no oczywiscie mozna wziasc dane z licznika - niestety problem jest z matchowaniem odczytu z faktura. Nie widze zadnego jednoznacznego ID.

**Comment by Santanachia** [comment]
@pawelhulek oznaczyłeś jako zrobione, ale nadal się nie wyświetla :(

**Comment by pawelhulek** [comment]
Issue jest oznaczone jako close głównie z tego powodu ze API nie zwraca wszystkim klientom zuzycia. Nie jest mozliwe naprawienie tego w sensowny sposób.
