### ISSUE TITLE
jak nie stracić danych?

### ISSUE THREAD

**Issue by Santanachia** [pawelhulek/pgnig-sensor#45]
Hej, w edycji dashboardu energii mam coś takiego:
![image](https://user-images.githubusercontent.com/4628507/194061724-a4e7f3ae-615a-454d-8cce-d50c3f19fd64.png)
chciałbym wykasować obecny sensor i dodać na nowo, ale obawiam się, że utracę zapisane wcześniej wartości.

Jakaś podpowiedź jak to naprawić?

**Comment by pawelhulek** [comment]
Oj nie mam pojecia.

Mozesz zawsze postawic sobie HA lokalnie w dockerze i zobaczyc jak sie zachowa po 1 odczycie, usunieciu sensora i dodanie go ponownie. bardzo prawdopodobne ze dane CI zostana. Mozesz tez sobie wyrownac state encji recznie w narzedziach developerskich.
