### ISSUE TITLE
powielanie encji

### ISSUE THREAD

**Issue by VonXavier** [pawelhulek/pgnig-sensor#48]
od czasu do czasu stare encje staja się niedostępne a w to miejsce pojawiaja się nowe.
przeszkadza to w skutecznym zbieraniu historii

**Comment by pawelhulek** [comment]
Nie jestem w stanie tego wygenerowac, moglbys pokazac o co dokladnie chodzi?

Swego czasu byla jedna taka zmiana gdy zostal dodany rozszerzony id encji, ale samoczynnie raczej to sie nie powinno zmieniac.

**Comment by VonXavier** [comment]
![Screenshot_20221217_215809](https://user-images.githubusercontent.com/52158891/208265923-60e03f22-8773-4e0d-9193-0a4ef41abdfa.jpg)
I działający
![Screenshot_20221217_220109](https://user-images.githubusercontent.com/52158891/208265941-996524fa-16c8-432c-9e62-cbe0df203d7d.jpg)

**Comment by pawelhulek** [comment]
@VonXavier Nie do konca wiem co mi tutaj pokazujesz teraz? CHetnie zobaczyłbym dane z urzadzenia z integracji - tam sie powinny wszystkie encje zgrupowac. Aczkolwiek podejzewam ze CI zmienili w PGNIG ID licznika i sie nowy sensor utworzył.

**Comment by VonXavier** [comment]
nie wiem gdzie tego szukać? mam to jeszcze z hacs.
licznik nie był zmieniany, co miesiąc spisuje ręcznie jego stan na stronę gazowni.
Encje wywala raz na jakiś czas. nie zauważyłem zależności czasowej itp. pierw myślałem ze zależy od aktualizacji a potem ze od częstotliwości podawania licznika, ale nic z tego się nie potwierdziło.

**Comment by pawelhulek** [comment]
Chodzilo mi o wejscie w 
Ustawienia > Urzadzenia oraz usługi > kafelek Pgnig sensor > kliknac w jedno urzadzenie i sprawdzic ile tam masz encji - powinies miec 3. Jak jest wiecej to znaczy ze cos PGNIG pozmieniał IDki
![image](https://user-images.githubusercontent.com/23282790/211637920-ba58adaf-9d72-490b-b950-2e9889a08aae.png)

**Comment by VonXavier** [comment]
ok, integracje mam przez hacs, encji jest 3
w dodatkach nie mam tej integracji.
czy usunąć z hacs a dodać poprzez integracje?

**Comment by pawelhulek** [comment]
Co masz na mysli przez dodatki?

Bardzo ciezko jest mi zrozumiec problem jaki masz wlasciwie problem.

Mowisz ze znikaja stare encje a pojawiaja nowe, ale z drugiej strony piszesz ze masz 3 encje. Na wykresie historii zmienia sie ich stan z x na 0, 0 na x1, x1 na 0, czy moze jeszcze inna kombinacja? Bardzo bym prosił o bardziej szczegółowe opisanie problemu.

**Comment by pawelhulek** [comment]
@VonXavier aktualne?

**Comment by pawelhulek** [comment]
@VonXavier Podbijam. Problem dalej wystepuje?

**Comment by VonXavier** [comment]
Nie zauważyłem.

niedz., 15 paź 2023, 17:16 użytkownik Paweł Hulek ***@***.***>
napisał:

**Comment by pawelhulek** [comment]
To jak nie wystepuje to zamykam - jakby co prosze o nowy issue, albo reopena
