### ISSUE TITLE
Jak często sensor aktualizuje dane ?

### ISSUE THREAD

**Issue by MrLupa** [pawelhulek/pgnig-sensor#49]
Jak często sensor aktualizuje dane i czy da sie to jakoś zmienić ?

**Comment by pawelhulek** [comment]
Tak z pamieci to co 8h.

Nie da sie zmienic na ten moment. Masz jakis usecase zeby odswiezac te dane czesciej?

Pamietaj prosze ze ta integracja pobiera dane z eboku PGNIG - nie zapewnia odczytu na zywo z Twojego licznika.
