### ISSUE TITLE
Brak odczytu kwoty z faktury

### ISSUE THREAD

**Issue by artblue1** [pawelhulek/pgnig-sensor#52]
PGNiG Gas Invoice Sensor pokazuje cały czas 0,00 zł. Działa jedynie pobieranie wartości odczytów. PGNiG Gas Coast Tracking - nieznany.

**Comment by pawelhulek** [comment]
@artblue1 Masz moze bledy w logach? Powinno sie coś sypnąć.

**Comment by artblue1** [comment]
Jedyne w logach co znalazłem to:

ERROR (MainThread) [homeassistant.components.sensor] Platform pgnig_gas_sensor does not generate unique IDs. ID pgnig_sensor***** already exists - ignoring sensor.pgnig_gas_sensor_*****

**Comment by pawelhulek** [comment]
hmmm. A jaka masz wersje? Próbowałes moze zmieniac id tego sensora?

Od kiedy korzystasz z integracji? Czy miałes juz fakture na eboku od czasu jej instalacji?

**Comment by pawelhulek** [comment]
@artblue1  Dziala Ci na obecnej wersji? Od kiedy korzystasz z integracji? Kiedy miales ostatnio fakture?

**Comment by artblue1** [comment]
Zainstalowałem wersję 2.3.5 usuwając poprzednią (nie miałem aktualizacji). Nadal to samo. 

PGNIG Gas Cost Tracking Sensor - nieznany
PGNIG Gas Invoice Sensor - 0,00zł

Może problem jest w tym, ze mam nadpłaty w pgnig? I kwoty "do zapłaty" na fakturach mam 0 zł? Tak mi teraz do głowy przyszło. Jeżeli tak to wtyczka powinna pobierać inaczej kwotę. 

Tutaj:
https://ebok.pgnig.pl/crm/get-invoices-v2?pageNumber=1&pageSize=12&api-version=3.0

widzę:

"GrossAmount": 67.93,
"AmountToPay": 0,

Może tutaj jest pies pogrzebany? ;)

**Comment by pawelhulek** [comment]
Nie powiem, robiłem ta integracje troche pod siebie. Osobiscie robie sobie automatyzacje na ilosci do zaplacenia - notyfikacje. Jak przestaniesz nadpłacać, to zacznie Ci sie dobrze wyświetlać ;)

**Comment by artblue1** [comment]
A duży kłopot zmienić na odczyt GrossAmount zamiast AmountToPay? Wtedy integracja by działała i u użytkowników płacących na bieżąco jak i u tych co robią przedpłaty ;)

**Comment by DEF2-E86A** [comment]
U mnie również nie działa. 2 tygodnie temu prosiłem o pomoc bo stan encji wisiał cały czas jako nieznany. Po zainstalowaniu wersji zaproponowanej jako 2.3.5 beta wskazania zmieniły na stan "0 zł" więc teoretycznie problem został rozwiązany jednak po wystawieniu nowych faktur które przyszły 2 dni temu stan odczytu w integracji nadal pokazuje 0 zł. 
![image](https://github.com/pawelhulek/pgnig-sensor/assets/92045373/56497027-b586-4263-9258-995e5fae0236)

**Comment by pawelhulek** [comment]
> oc bo stan encji wisiał cały czas jako nieznany. Po zainstalowaniu wersji zaproponowanej jako 2.3.5 beta wskazania zmieniły na stan "0 zł" więc teoretycznie problem został rozwiązany jednak po wystawieniu nowych faktur które przyszły 2 dni temu stan odczytu w integracji nadal pokazuje 0 zł.
> Od czas wgrania nowej wersji 2.3.5 minęło 2 tygodnie i encja pokazuje że aktualizowała się 2 tygodnie temu

Niestety ale duzy, wczesniej ludzie zglaszali ze maja kilka liczników wiec ta kwota tam jest kumulacja wszystkich niezaplaconych faktur.

Natomiast sama wartosc gross_amount jest dostepna jako atrybut 

>  Cost Tracking Sensor

` 
Last invoice gross amount
`

Czy takie cos Cie urzadza?

@DEF2-E86A Jesli uwazasz ze Twój problem nie został rozwiany w https://github.com/pawelhulek/pgnig-sensor/issues/53 to bardzo bym prosił o reopen, ewentualne kontynuowanie dyskusji tam. Cieżko stwierdzić czy te 2 problemy są powiązane.

**Comment by wizu** [comment]
U mnie także brakuje kwoty z faktury. Co miesiąc sam podaję stan licznika przez aplikację i płacę za to co zużyłem.
API zwraca mi:
`      "GrossAmount": 845.960,
      "AmountToPay": 0.0,
      "Wear": 0.0,
      "WearKWH": 2802.000,
`
Nie wiem czy AmountToPay jest 0, bo tę fakturę już opłaciłem, czy tak jest u mnie zawsze. Sprawdzę przy następnej fakturze.

Czy mógł byś dodać jako atrybut do encji sensor.pgnig_gas_sensor_... dodać te 4 pola? Wtedy sam bym sobie policzył co trzeba. 
Ja i tak potrzebuję cenę za kWh, a nie m3.

**Comment by pawelhulek** [comment]
@wizu Problem z dodaniem jest taki, że przy przyjsciu np 2 faktur do zaplacenia (jedna za gaz, druga odsetkowa) i oplaceniu obydwóch, to do konca nie wiem które gross amount i wearKWH mam wziasc, z odsetkowej czy zwyklej - nie jestem pewien czy da sie je rozroznic.

Z ciekawości do czego CI KWH i cena za KWH potrzebna? 
Jestem ciekaw, bo HA do dashboardów energi przyjmuje tylko m3

**Comment by wizu** [comment]
Ja mam dashboard energi skonfigurowany z kWh dla gazu i działa to poprawnie. Kilka wersji do tyłu dodali wsparcie.
U używam kWh bo odczytuję z pieca gazowego Vaiilant ile energii używa na centralne, a ile na ciepłą wodę. I te dane mam w kWh właśnie.

**Comment by pawelhulek** [comment]
@wizu Popatrzyłem jeszcze raz na twój case.
Jesli chodzi o dodanie pól do pgnig_gas_sensor to nie jest to ten moment osiągalne. Problem jest taki ze sa 2 endpointy: jeden na odczyty i jeden na faktury. Ten na odczyty ma dane tylko o m3 odczytanych ( to jest wlasnie ten gas_sensor)

Natomiast ten na faktury ma dane w kwh. Nie da sie tych wartosci z 2 endpointów skorelowac maszynowo. 

Dodatkowo ten do Invoices opiera sie na wyswietlaniu tylko faktur nie oplaconych ( on ma jako atrybuty kumulowane zuzycie w KWH i kumulowane gross_amount, a także date płatności, ma tez wartosc w m3 - ale wydaje mi sie ze akurat ta wartosc jest wycofywana z endpointa przez pgnig)


Co mógłbym zrobic to ewentualnie eksperymentalny sensor, gdzie bylyby akumulowane odczyty w kwh i akumulowane gross_amount z tych faktur. Jedyne co mnie do tego zbytnio nie zachęca to fakt, że sensory Invoices i Cost Tracking powoduja lawine issuesów i działaja różnie u różnych osób.

**Comment by wizu** [comment]
![Screenshot_2024-01-06-12-21-36-44_c3a231c25ed346e59462e84656a70e50](https://github.com/pawelhulek/pgnig-sensor/assets/1247507/6a3d76e7-8c99-4926-b67f-efe42987730a)
Z sensora faktury będę sobie w stanie to wyciągnąć. Zrobię sobie automatyzację która mi to zapisze do helpera number.

**Comment by pawelhulek** [comment]
Jak rozumiem poradziles sobie na encji faktury. Zamykam
