### ISSUE TITLE
Logowanie przez Google

### ISSUE THREAD

**Issue by zamojski** [pawelhulek/pgnig-sensor#55]
Do e-boku PGNiG loguję się kontem Google. Czy mogę skorzystać z integracji w jakiś sposób?

**Comment by czerwony03** [comment]
Musisz zresetować hasło i skonfigurować integracje loginem/hasłem. Logowanie za pomocą Google powinno ciągle działać poprawnie.

**Comment by pawelhulek** [comment]
@zamojski Daj znac czy pomoglo - dopisze do docsów.

**Comment by zamojski** [comment]
Zresetować się nie da, bo:

> Brak możliwości zresetowania hasła - zweryfikuj czy konto nie zostało aktywowane poprzez serwis zewnętrzny (Facebook/Google/Apple).

Jeżeli założę drugie konto na email i hasło to będę mógł powiązać umowę? Chociaż to wszystko dziwne, bo mam zapisane w Keepassie login i hasło tylko one nie działają.

**Comment by zamojski** [comment]
Niestety założyć konta na ten email już się nie da:

> Wystąpił błąd. Zweryfikuj poprawność danych i upewnij się, czy nie posiadasz już konta eBOK. Jeżeli już posiadasz konto w serwisie - pamiętaj, że możesz skorzystać z funkcji "Zresetuj hasło"

Podejrzewam, że na tym samym emailu się nie da, bo jest identyfikatorem w systemie.

**Comment by pawelhulek** [comment]
@zamojski Udało sie zalogowac koniec konców? Chetnie dopisałbym do readme.

**Comment by zamojski** [comment]
Odpuściłem sobie i zrobiłem helper do ręcznego wprowadzania :⁠-⁠)
