### ISSUE TITLE
Brak urządzeń lub encji

### ISSUE THREAD

**Issue by b3cksy** [pawelhulek/pgnig-sensor#56]
Cześć,
Od jakiegoś już czasu mam ten problem, tzn "brak urządzeń lub encji". Ponowne wczytywanie, pobieranie, itp. nie przynosi skutku. Szkoda, że mi to nie działa, bo integracja jest naprawdę bardzo przydatna.

Log poniżej. 
> 
> 2023-10-31 14:22:24.495 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up pgnig_gas_sensor platform for sensor
> Traceback (most recent call last):
>   File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 38, in async_setup_entry
>     pgps = await hass.async_add_executor_job(api.meterList)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pgnig_gas_sensor/PgnigApi.py", line 31, in meterList
>     return ppg_list_from_dict(dictionary)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pgnig_gas_sensor/PgpList.py", line 139, in ppg_list_from_dict
>     return PpgList.from_dict(s)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pgnig_gas_sensor/PgpList.py", line 119, in from_dict
>     ppg_list = from_list(PpgListElement.from_dict, obj.get("PpgList"))
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/pgnig_gas_sensor/PgpList.py", line 25, in from_list
>     assert isinstance(x, list)
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 40, in async_setup_entry
>     raise ValueError
> ValueError

**Comment by pawelhulek** [comment]
hmm dziwne - wyglada jakbys nie mial liczników podpietych.
Mógłbys wywołac endpoint https://ebok.pgnig.pl/crm/get-ppg-list?api-version=3.0
i wrzucic tutaj odpowiedz - tylko bardzo bardzo prosze - zamaskuj dane prywatne - takie jak numery liczników adresy.

**Comment by b3cksy** [comment]
> hmm dziwne - wyglada jakbys nie mial liczników podpietych. Mógłbys wywołac endpoint https://ebok.pgnig.pl/crm/get-ppg-list?api-version=3.0 i wrzucic tutaj odpowiedz - tylko bardzo bardzo prosze - zamaskuj dane prywatne - takie jak numery liczników adresy.

Dzięki za odpowiedź. Wygląda to następująco:
![image](https://github.com/pawelhulek/pgnig-sensor/assets/102021737/f4ac566c-57a6-44a7-8b43-902a27cc5571)

**Comment by pawelhulek** [comment]
@b3cksy Wybacz za poślizg. 

Dalej nie bangla?

**Comment by pawelhulek** [comment]
@b3cksy  Dalej nie dziala?

**Comment by b3cksy** [comment]
Dalej nie działa. Sprawdzone przed chwilą.
![image](https://github.com/pawelhulek/pgnig-sensor/assets/102021737/01bb29dd-a0c6-4f9b-a074-a0389fcd5340)

**Comment by b3cksy** [comment]
w między czasie stawiałem nową instancję HA i tam też nie działa :|

**Comment by pawelhulek** [comment]
@b3cksy Przygotowałem na ślepo poprawkę, z danych które podesłałes wynika, że powinno działać 🤔  Mógłbys zainstalować i dać znać czy działa - usunąłem asercje na to czy obiekt z licznikami z API to jest lista? 

Wersja: `56-brak-urządzeń-lub-encji`

![image](https://github.com/pawelhulek/pgnig-sensor/assets/23282790/394f775f-6f91-4348-af64-a461de5da1ff)

**Comment by b3cksy** [comment]
Wykonałem tę usługę co podesłałeś (ale poprzez tryb yaml, bo nie mam żadnym encji do wybory za wyjątkiem zainstalowanych dodatków) i bez zmian. 

w logach dalej to samo, tj:
2024-01-31 10:44:10.045 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up pgnig_gas_sensor platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 38, in async_setup_entry
    pgps = await hass.async_add_executor_job(api.meterList)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pgnig_gas_sensor/PgnigApi.py", line 31, in meterList
    return ppg_list_from_dict(dictionary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pgnig_gas_sensor/PgpList.py", line 139, in ppg_list_from_dict
    return PpgList.from_dict(s)
           ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pgnig_gas_sensor/PgpList.py", line 119, in from_dict
    ppg_list = from_list(PpgListElement.from_dict, obj.get("PpgList"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pgnig_gas_sensor/PgpList.py", line 25, in from_list
    assert isinstance(x, list)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 40, in async_setup_entry
    raise ValueError

**Comment by pawelhulek** [comment]
Hmm, dziwne - a powiedz mi czy po zaaplikowany tej zmiany zrestartowałes HA?

**Comment by b3cksy** [comment]
Oczywiście.

W dniu 31 sty 2024, 18:30, o 18:30, użytkownik "Paweł Hulek" ***@***.***> napisał:

**Comment by pawelhulek** [comment]
Hmmm a versja dodatku tez sie zmieniła?

Wykonany sewis z yamla był takI? 
```

service: update.install
target:
  entity_id: update.pgnig_sensor_update
data:
  version: 56-brak-urządzeń-lub-encji
```


Na taka jak na obrazku?
![image](https://github.com/pawelhulek/pgnig-sensor/assets/23282790/259e30a9-4fbc-46db-b0d9-1efe9b8b7157)

Wybacz ze dopytuje, ale kod ze stacktracu nie istnieje na tej wersji która zainstalowałes.

**Comment by maciejbuchert** [comment]
Jeśli dobrze doczytałem.
Taryfa W-3.6 działa na zasadach prognozowanego zużycia.

Przez co w eBOK nie ma możliwości podania odczytu i "brakuje licznika".

Rozwiązaniem będzie przejście na taryfę W–3.12T i podawanie odczytu ręcznie
