### ISSUE TITLE
Brak danych w zakładce "Energia"

### ISSUE THREAD

**Issue by maciejbuchert** [pawelhulek/pgnig-sensor#62]
Cześć.
Mam wpięty licznik i wszystko działa poprawnie
![image](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/6defb699-37a5-4c6f-b158-c1617e2b40c9)

Jednak w zakłace "Energia" nie mam żadnych informacji
![image](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/033b3acc-a615-41ee-87d4-d9ceead1ab69)
![image](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/9df4fd90-dcb2-4710-a738-4400df359420)

Jak widać w konfiguracji wszystko jest ok.
![Zrzut ekranu 2024-06-23 o 11 45 40](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/075d2bf1-ca81-49b9-8590-9307e6ee5c5b)

Jakieś pomysły?

**Comment by pawelhulek** [comment]
W zakladce energia zuycie gazu pokazuje sie tylko w dniu w ktorym nastapiła zmiana. 
Sprawdz proszę granulacje miesięczną, albo roczną na wykresie - wtedy powinno sie pojawić.

Z ciekawości cost tracking sensor działa Ci? z Tego co zauwazylem z API zaczęło znikać wartość pól potrzebnych do jego wyliczenia.

**Comment by maciejbuchert** [comment]
Racja. W widoku rocznym już to wygląda
![image](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/b44264b9-a8e2-450a-a209-8a6ac88d4d9c)

Widzę, że cena działa
![image](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/6bbf4493-ab0c-4b7d-8234-73c0c7b6392f)

Chociaż tutaj nie potrafi policzyć kosztów
![image](https://github.com/pawelhulek/pgnig-sensor/assets/9607667/de2bfba4-1e89-401d-b5ca-2dfa71cc4a6e)
