### ISSUE TITLE
HomeAssistantType was used from pgnig_gas_sensor, this is a deprecated alias

### ISSUE THREAD

**Issue by wdoganowski** [pawelhulek/pgnig-sensor#65]
HomeAssistantType was used from pgnig_gas_sensor, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'pgnig_gas_sensor' custom integration

**Comment by pawelhulek** [comment]
Dzieki za info - duplikat: https://github.com/pawelhulek/pgnig-sensor/issues/63
