### ISSUE TITLE
Podanie stanu licznika

### ISSUE THREAD

**Issue by VoyteckPL** [pawelhulek/pgnig-sensor#66]
Czy dałoby się dodać obsługę podania stanu licznika?
Mam odczyt z licznika na posesji i chciałbym raz w miesiącu podać stan licznika automatyzacją bez logowania się na stronę itd.
Będę wdzięczny za pomoc.

**Comment by pawelhulek** [comment]
Dałoby się natomiast nie jest to w moich planach - API nie jest oficjalne wiec nie chciałbym tutaj dodawać możliwości spamowania serwer PGNIG odczytami.
Zamykam wątek - pomysł  jest otwarty tutaj: https://github.com/pawelhulek/pgnig-sensor/issues/50
