### ISSUE TITLE
cannot update to 0.1.4

### ISSUE THREAD

**Issue by kayserjan** [pawelhulek/pgnig-sensor#7]
Hello,
thx for the integration you provided. It works fine on version 0.1.3.

The struggle that I get is the update to 0.1.4.
I trigger the update via HACS and looks like it's not getting processed :(
I wait a relatively long time (120s) and when I'm requested to restart HA. 
I do it, nevertheless, the update is not installed.

I've tried again - no luck.
I have tried removing the 0.1.3 and installing 0.1.4 from scratch - no luck.
I can install 0.1.3 from scratch - this works.

I'm attaching the HACS diagnostics data.

[config_entry-hacs-adc2947298cac286b0def42b62d7c4f2.json.txt](https://github.com/pawelhulek/pgnig-sensor/files/8370494/config_entry-hacs-adc2947298cac286b0def42b62d7c4f2.json.txt)

Would you mind taking a look?

**Comment by pawelhulek** [comment]
Hi @kayserjan I have to admit i have no Idea why this is integration doesn't want to update. From the diagnostic file it looks like it is updated in most of the places but not on the custom_components level.

I can only advice to install it manually. I mean clone the repo and move custom_components/pgnig_gas_sensor/ dir to your HA /custom_components folder.

**Comment by pawelhulek** [comment]
Please try newest version.
