### ISSUE TITLE
Niezapłacone faktury?

### ISSUE THREAD

**Issue by majkers** [pawelhulek/pgnig-sensor#8]
Witam,
super robota! A dałoby radę dorobić sensor(y) dla najbliższej niezapłaconej faktury i/lub faktur prognoz? Np. jeden sensor - jedna faktura?

**Comment by majkers** [comment]
Ja myślałem, że raczej jedna faktura=jedna encja, są faktury prognozy i bieżące. Ta jedna encja miałaby kwotę wszystkich, czy tylko najbliższej? A co do API to chyba wyjdzie w praniu. Generalnie data i kwota najważniejsze.

**Comment by pawelhulek** [comment]
Zobacz prosze na wersje 1.0.1 czy taki format Ci pasuje. Zrobilem to na jednej encji ktora podlicza ile zostalo do zaplacenia i do kiedy najblizsza platnosc.

**Comment by majkers** [comment]
Na razie nie mam żądnych niezapłaconych faktur. Jednak jak to będzie kwota wszystkich niezapłaconych faktur prognoz to trochę słabo... bo ja dostaję rachunki na ok rok z góry i chciałbym wiedzieć ile do zapłaty z jakim terminem w najbliższej

**Comment by pawelhulek** [comment]
@majkers Dodałem kwote do zaplacenia z najblizsza faktura do atrybutów. Mam nadzieje ze to rozwiazuje Twój przypadek. Sprawdz wersje 1.0.2
