### ISSUE TITLE
Czego nie wiem?

### ISSUE THREAD

**Issue by PioSkot** [pawelhulek/pgnig-sensor#9]
Uruchomiłem integrację... ale po początkowym pobraniu wartości (stan na instalację) nic się nie zmienia, tak jakbym nie używał gazu. 
Co zrobiłem źle?

**Comment by pawelhulek** [comment]
Zamykam. Myśle że to powinno odpowiedziec na Twoje wątpliwości. Gdyby jednak byl rozjazd pomiedzy odczatami z Eboku PGNIG a integracja to prosiłbym o kontakt.
